### ISSUE TITLE
unable to compile on ubuntu

### ISSUE THREAD

**Issue by silas101** [JeffreyBLewis/gpuideal#2]
I receive the following error when trying to compile on Ubuntu 16.04 (and 18.04):

/usr/local/cuda-9.0/bin/nvcc -c -Xcompiler "-fpic   -g -O2   " -D_FORCE_INLINES -I.  -I/usr/lib/R/include  -I./Random123-1.09/include ideal.cu -o ideal.o
ideal.cu:1:15: fatal error: R.h: No such file or directory
compilation terminated.
Makefile:29: recipe for target 'ideal.o' failed

I was able to compile by changing line 1955 in 'configure' to the actual path of R_INCLUDE (/usr/share/R/include). 

I get a warning after the compile completes but doesn't seem to be an issue:

ideal.cu(102): warning: function "d_rtnorm_met" was declared but never referenced

**Comment by JeffreyBLewis** [comment]
Sorry for my slow reply on this.   The warning that you note is innocuous.
